apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samousse-pvc
  namespace: samousse
spec:
  storageClassName: sc-lvm
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi